language: java
sudo: false
jdk:
    - oraclejdk8
install: true
addons:
    apt:
        packages:
            - oracle-java8-installer
script: 
    - mvn clean verify
after_success:
    - mvn jacoco:report jacoco:report-integration coveralls:report
